### ISSUE TITLE
Responsiveness of e-mails

### ISSUE THREAD

**Issue by henkjanverkerk** [changer/sc-messages#30]
In short, the current e-mail template is non responsive. Gmail app modifies it to show readable, but the original one is not responsive.
Also, in some cases, the e-mail is interpreted as a previous e-mail/signature and is collapsed.
![img_0303](https://cloud.githubusercontent.com/assets/1519497/8499426/253a0cf8-2193-11e5-992d-a39ebba305ad.PNG)
![img_0305](https://cloud.githubusercontent.com/assets/1519497/8499429/2c3bcd7a-2193-11e5-8c5a-8dd968751575.PNG)
![img_0304](https://cloud.githubusercontent.com/assets/1519497/8499433/31122218-2193-11e5-9e31-cc34f6b1ba0f.PNG)

**Comment by josjevv** [comment]
duplicate with https://github.com/bulletind/khabar/issues/83
