### ISSUE TITLE
[IncidentChanger] Spellingissue in email (very-high)

### ISSUE THREAD

**Issue by madhums** [changer/sc-messages#31]
_From @changertesting on July 14, 2015 11:33_

Windows IE11

In a receiving email there is writte 'very-high' (with stripe). In the application there is everywhere 'very high' written (without stripe).

![spelling issue very high](https://cloud.githubusercontent.com/assets/8101020/8672225/ae66a8d2-2a2c-11e5-8fd8-2cc3ee3ac0be.png)

Please write this in all emails also as 'very high' (without stripe).

_Copied from original issue: changer/sc-client#459_

**Comment by henkjanverkerk** [comment]
https://github.com/changer/spystore/blob/develop/incidentapp/hooks.go#L114
